### ISSUE TITLE
Handling of apostrophe

### ISSUE THREAD

**Issue by Kileak** [OpenToAllCTF/OTA-Challenge-Bot#102]
Currently OTA bot doesn't like when users are using single apostrophes, since `shlex` fails on splitting the arguments with "No closing quotation found".

We could get around this by foregoing on using single quotes for enclosing multiple words (could still use double quote for this) and just escape the apostrophe before lexing it.

Thoughts on this?

**Comment by Corb3nik** [comment]
@Kileak Check this out : https://docs.python.org/2/library/shlex.html#shlex.shlex.quotes

We could simply not take any quotes into consideration. Problem solved, I think...

**Comment by Corb3nik** [comment]
Maybe `shlex` isn't the right function to work with to parse commands either.

**Comment by Kileak** [comment]
We might want to allow quotes for specifying descriptions (think of challenge long names for Solve Tracker for example), so I'd just remove single quote for this
