### ISSUE TITLE
Should BotServer lock be an instance attribute?

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#127]
As a class attribute we cannot instantiate more than one

**Comment by Kileak** [comment]
Why would we want to start more than one botserver instance?

Slack API throtteling would be just one hindrance. Also I don't see an advantage for multiple instances, all listening to the same `!commands` and messing with the same pickle db (also botserver resembles the bot user itself).

If we'd need multiple bot users, one could start them from different directories, which would be safer to use anyways.
