### ISSUE TITLE
Don't allow !workon after solve

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#140]
Don't want people to join the challenge just to steal the flag.

Maybe allow it only to solver, or maybe only people who were already in the channel at some point?

**Comment by reznok** [comment]
If this happens, should allow access after the CTF ends so that people can go review after.

**Comment by Kileak** [comment]
We should add a `!endctf` command anyways to flag the ctf as ended, so the unsolved challenges won't show up anymore in status (might add another issue for that), and people won't be able to add new challenges (but without archiving the ctf directly). 

This could then also open up all challenge channels again.

We might also add

- admin command to toggle this on/off for running ctfs
- add parameter to `addctf` for disabling this on ctf creation (default: on) (?)

**Comment by Kileak** [comment]
You cannot `!workon` on solved challenges anymore (except admins).

When a ctf is marked as ended, everyone can join solved challenges again.

If someone needs absolutely to join a solved challenge, an admin can put him into the channel with `!as @user workon challenge` (`as` commands were refactored, so the specified user is handled as an admin for this command).
