### ISSUE TITLE
Add command to just list running CTFs (and their channels), without challenges

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#147]

**Comment by Kileak** [comment]
Fixed by 2722975d76dd09fd6ffc28a54ecfe25c20bfc275

Didn't try to be too creative on the output

![image](https://user-images.githubusercontent.com/6137334/44024272-1cbfc9a2-9eed-11e8-85ae-dd3e102f9237.png)

If it's fine, close, otherwise change output :)

**Comment by Grazfather** [comment]
You're the best.

Let's give it a shorter name? maybe !ctfs or something?

**Comment by Kileak** [comment]
If not in a ctf channel, `!status` will now show short status as default (can be overridden with `-v` for showing full status in a non ctf channel).
