### ISSUE TITLE
!invite command

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#151]
1. Allow to invite to private CTFs -- should we make this admin only?
2. Allow for other channels... just for convenience.
  * Slack is stupid and won't let you `/invite` a list of people if any of them are already in the channel. Our command wouldn't be stupid like that.

**Comment by mzfr** [comment]
@Grazfather this can be closed now.

**Comment by Grazfather** [comment]
Fixed in #175
