### ISSUE TITLE
Automatize new challenge ping for OTAu

### ISSUE THREAD

**Issue by DIDIx13** [OpenToAllCTF/OTA-Challenge-Bot#162]
Instead of @Corb3nik doing all the _hard_ work of pinging @chaine with New challenge + challenge description, why not use bishop to take care of this part.

![corb example](https://puu.sh/Cd5az/5963e02c2d.png)

**Comment by Kileak** [comment]
How would you expect OTA-Challenge-Bot doing this?

**Comment by Kileak** [comment]
Since the bot has no connection to otau in any way, the only ways to do this, would be to either add a new command for posting this (which would mean more work, than just posting it to the channel) or scraping the otau challenge page for new challenges (which is no option).
