### ISSUE TITLE
Log 'sketchy' behaviour

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#196]
e.g. log when people deleted `!workon` messages.

**Comment by Kileak** [comment]
Fixed with 0e7cf892a82f7b2da08db85020c364a28e0256c6

`delete_watch_keywords` can be set to a comma separated list of keywords like `workon, reload, endctf` and the bot will log, if someone deletes a message containing one of those keywords.
