### ISSUE TITLE
Linksave command isn't intuitive

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#202]
Personal opinion : I'm not a big fan of the command names for the link saving feature.

```
`!linksave link <category>`
    (Save a link in one of the categories: web, pwn, re, crypto, misc)
`!linksave showlinkurl`
    (Show the url for linksaver repo)
```

The commands are either too long, or not intuitive (`!linksave link` for example).

May I suggest a change for something simpler like `!savelink` (which will also display the URL where it was saved.)?

I would also get rid of the `!linksave showlinkurl`. Maybe we could add the link directly in the `help` description of the `!savelink` command.

**Comment by Kileak** [comment]
You know that you don't have to give the handler name in the command?

`!link pwn`
`!showlinkurl`

are the commands, everybody is using.

**Comment by Corb3nik** [comment]
Ah right.

Fair enough 👍
