### ISSUE TITLE
Linksave handler does not capture complete URL

### ISSUE THREAD

**Issue by ujjwal96** [OpenToAllCTF/OTA-Challenge-Bot#204]
The regex [here](https://github.com/OpenToAllCTF/OTA-Challenge-Bot/blob/development/handlers/linksave_handler.py#L32) does not capture the params in a url.

Possible fix - http://www.noah.org/wiki/RegEx_Python#URL_regex_pattern

**Comment by Kileak** [comment]
@ujjwal96 was this fixed with your last pr?
