### ISSUE TITLE
Have bot add reminder to archive channel a week after finishing/ending

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#206]
e.g. make it run `/remind <admins> in one week to archive <ctfname>`

**Comment by wbowling** [comment]
The status command could also say how long the ctf has been finished for

**Comment by Kileak** [comment]
First draft:

![image](https://user-images.githubusercontent.com/6137334/59784380-8e497400-92c2-11e9-99d2-55d8c134a643.png)

**Comment by Grazfather** [comment]
looks good. I'd say lower the granularity (we don't care about minutes and seconds) and instead of "finished since {}" do "finished {} ago"

**Comment by Kileak** [comment]
Reminders added with 8b2c954b262602237a69f469bc011fffae57162a

This will

- create a reminder with the configured offset (in hours) for every admin user
- when the ctf gets archived, the bot will remove all the reminders he created for the corresponding ctf

*Upcoming*:
• “CTF time4 - time4 (#time4) should be archived.” at 12:32AM tomorrow
