### ISSUE TITLE
workon command should work with bold text

### ISSUE THREAD

**Issue by afrigon** [OpenToAllCTF/OTA-Challenge-Bot#218]
When copy-pasting challenge name from the status list, the command will fail because of the bold style.

![image](https://user-images.githubusercontent.com/33911560/82137287-b5673900-97e4-11ea-92e8-5954bbd03d23.png)

**Comment by Corb3nik** [comment]
bruh.

**Comment by wbowling** [comment]
@Corb3nik I have done this almost every ctf, super annoying :P should either work with bold text or make the status not bold. 

Just had a rough count through our defcon quals channel and it happened 14 times at least

**Comment by Corb3nik** [comment]
Yeah, I think we should make it work by keeping the bold text.

**Comment by Kileak** [comment]
Fixed with e3e6ac5be5903872d509923fa8e35f090c1a9069
