### ISSUE TITLE
!ctf archiveall command

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#29]
I propose adding a `!ctf archiveall` command to archive all *challenge* channels once the CTF is over. 
The main CTF channel would remain intact. 

This will be great to keep the slack clean, instead of running `/archive` on each channel manually.

**Comment by Kileak** [comment]
Will the api check if the triggering user has some special rights to do so?

If not, we should add "admin" accounts for commands like this, or making this available through the config console. Otherwise it would open the door for trolling.

**Comment by Corb3nik** [comment]
Agreed, what would be the best approach for this? Username whitelists?

**Comment by Kileak** [comment]
Sounds good and might be the easiest way to handle this.

- UserIDs could be added on console (something like `admin U898d778`) and stored in the json
- Users in that list might get access to "admin commands"
- Admin commands could be marked in the CommandDescriptor with a special flag, so they wouldn't show up in the usage for normal users

**Comment by wbowling** [comment]
Renaming a ctf should probably be an admin command too

**Comment by Corb3nik** [comment]
An alternative would be : https://api.slack.com/docs/message-buttons
