### ISSUE TITLE
Creating challenge shouldn't assume you're working on it

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#42]

**Comment by Corb3nik** [comment]
We should use the "Assignees" in the github issues for that.

**Comment by Grazfather** [comment]
edited

**Comment by Corb3nik** [comment]
Ahhhh, this makes more sense. 

Should we just let the people working on the challenge create the channel?
Basically, if nobody is working on a challenge, no channel is created.

**Comment by Grazfather** [comment]
Naw I think anyone can create a channel and ota bit will hold it open.
Working on it will get you invited. That way u can keep the list of
available challenges up to date

**Comment by Corb3nik** [comment]
Should be fixed.
