### ISSUE TITLE
Rework Status Display

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#47]
The status display is too large and messy IMO.

I suggest the following :

**============= TWCTF2017 =============**
**> Solved**
:tada: **0xc5c2c3c4c9c3** (Solved by : vakzz)
:tada: **ascii_art_maker** (Solved by : kileak)
:tada: **freshen_uploader** (Solved by : corb3nik, kileak)
**> Unsolved**
[1 active] **led** : grazfather
[1 active] **pdromes_pair_chal** : _root
[2 active] **super_sec_storage** : corb3nik, vakzz

I'm taking into consideration that we will [make channels private](https://github.com/OpenToAllCTF/OTA-Challenge-Bot/issues/44).

Also we don't need the "active" section for solved challenges.

**Comment by Grazfather** [comment]
Works for me, but include #45 so that we don't get pinged so much.
