### ISSUE TITLE
Bot setting channel purpose takes the response as another command

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#52]
Maybe it only happens because I am using my own API key, maybe only I see it.

<img width="854" alt="slack_-_opentoall" src="https://user-images.githubusercontent.com/497310/30514296-c77a0f82-9ac6-11e7-87e9-1c1e78354483.png">

**Comment by Corb3nik** [comment]
The bot seems to be parsing events created by Slack itself : https://api.slack.com/events/message (see "Subtypes")

I'll make the bot filter out all events with subtypes. Normal messages don't have any subtypes.
