### ISSUE TITLE
support !solved not as self

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#59]
It'd be nice if there were a way to mark a challenge as solved without claiming you solved it. Maybe an admin command such as:

`!solveas oreos auir`

Or maybe a more general admin only command:

`!as oreos !solved`

**Comment by Corb3nik** [comment]
What's the use case though? Why would someone want to solve a challenge without claiming it :/ 

I'm scared that implementing this would decrease usage of the bot, since "someone else can run the command for me" lol

**Comment by Grazfather** [comment]
we don't have even show it in !help (maybe commands should have a hidden flag?). Some people won't use it regardless, and this'll let us keep the challenge list accurate. You're right though that we should prod people to use it first

**Comment by Grazfather** [comment]
The more general `as` command in #95 lets an admin run any command as anyone, so `solve` doesn't need to add support.
