### ISSUE TITLE
Renaming CTFs/Challenges

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#6]
In the event of a typo, members should be able to rename ctfs/challenges and their corresponding channel.

**Comment by Grazfather** [comment]
What's the value of this over deleting and recreating? Will it rename the channel?

**Comment by Kileak** [comment]
If it's possible to rename the channel with the api, it would keep the content of the channel, if the renaming isn't done instantly after creating the channel.

So, if it isn't too much work, why not, though it shouldn't have a high priority.

**Comment by Corb3nik** [comment]
It should be possible : https://api.slack.com/methods/channels.rename .

So renaming a CTF challenge should rename the channel + update the meta data in the `purpose` section with the new name.

**Comment by Corb3nik** [comment]
Should we be able to rename CTF channels to? @Kileak

**Comment by Kileak** [comment]
Only implemented for challenge for now, but can extend it for ctfs also, shouldn't be much work.
