### ISSUE TITLE
Make bot an email bridge

### ISSUE THREAD

**Issue by mercsw** [OpenToAllCTF/OTA-Challenge-Bot#63]
When adding a new CTF, a new email should be created that can be used to register for the CTF.

Something like OTA-<CTFNAME>-<RANDOMSTUFF>@somewhere.org

These emails would then get dump in the channel for everyone working on the CTF to see.

**Comment by Corb3nik** [comment]
We could have it generate credentials too.
- Email
- Username
- Password

**Comment by Kileak** [comment]
Don't really see the benefit, one would need access to this mail anyway to activate the ctf account, so why not just use a common mail account for this (or a personal)?

**Comment by Kileak** [comment]
Since we request to use the official ota mail, this seems to be obsolete anyways.
