### ISSUE TITLE
Solver Tracking

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-Challenge-Bot#72]
To keep track of solvers, I suggest creating a [Github project page](https://help.github.com/articles/user-organization-and-project-pages/).

Upon solve/archive, the bot would push a new blog post on the Project Page with the current solvers per challenge.

That info would then be available online for everyone :)

**Comment by wbowling** [comment]
I like this :) could also edited later by solvers to add links to write ups

**Comment by Kileak** [comment]
Added github support and pushing solve status to a project page.

For now just as an admin command `postsolves <Title> <filename_postfix>`. When it works well, this can also be appended to the solve and archive command, so it automatically updates the blog post.
