### ISSUE TITLE
!showcreds Returns Creds In Lowercase Form

### ISSUE THREAD

**Issue by reznok** [OpenToAllCTF/OTA-Challenge-Bot#96]
Example:
!ctf addcreds OpenToAll vLqyvh3A%Zsbq!F

!ctf showcreds

ota_bot [3:35 PM]
Credentials for CTF *insomni*
URL      : https://teaser.insomnihack.ch/
Username : opentoall
Password : vlqyvh3a%zsbq!f

**Comment by reznok** [comment]
Just noticed this is currently addressed by #92. Closing this issue.

**Comment by Grazfather** [comment]
Keep it open until the PR is merged.

**Comment by Grazfather** [comment]
My bad, I thought there was a PR but not an issue.
