### ISSUE TITLE
Add command to see head commit/branch

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#97]
Might be nice just to see what version we're running

e.g. `!version` -> "I am running commit ABCD1234, which is the tip of my *development* branch"

**Comment by Kileak** [comment]
Sounds nice, but how could we access this information at runtime?

Reading from `.git`?

**Comment by Corb3nik** [comment]
It sounds nice, but is this an issue that needs fixing?

**Comment by Grazfather** [comment]
Could just run a git command such as `git log -1 --pretty=format:"%h %d %s"`

```bash
[~/code/usercorn]$ git log -1 --pretty=format:"%h %d %s"
497ece3  (HEAD -> tui, origin/tui) plumbing for tui
```

**Comment by Kileak** [comment]
Added `!version`
